/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RediscoverRouteImport } from './routes/rediscover'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AddRouteImport } from './routes/add'
import { Route as ActivityRouteImport } from './routes/activity'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UHandleRouteImport } from './routes/u.$handle'
import { Route as MessagesHandleRouteImport } from './routes/messages.$handle'
import { Route as ArtistIdRouteImport } from './routes/artist.$id'
import { Route as AlbumIdRouteImport } from './routes/album.$id'

const RediscoverRoute = RediscoverRouteImport.update({
  id: '/rediscover',
  path: '/rediscover',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AddRoute = AddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UHandleRoute = UHandleRouteImport.update({
  id: '/u/$handle',
  path: '/u/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesHandleRoute = MessagesHandleRouteImport.update({
  id: '/messages/$handle',
  path: '/messages/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtistIdRoute = ArtistIdRouteImport.update({
  id: '/artist/$id',
  path: '/artist/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AlbumIdRoute = AlbumIdRouteImport.update({
  id: '/album/$id',
  path: '/album/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/add': typeof AddRoute
  '/auth': typeof AuthRoute
  '/profile': typeof ProfileRoute
  '/rediscover': typeof RediscoverRoute
  '/album/$id': typeof AlbumIdRoute
  '/artist/$id': typeof ArtistIdRoute
  '/messages/$handle': typeof MessagesHandleRoute
  '/u/$handle': typeof UHandleRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/add': typeof AddRoute
  '/auth': typeof AuthRoute
  '/profile': typeof ProfileRoute
  '/rediscover': typeof RediscoverRoute
  '/album/$id': typeof AlbumIdRoute
  '/artist/$id': typeof ArtistIdRoute
  '/messages/$handle': typeof MessagesHandleRoute
  '/u/$handle': typeof UHandleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/add': typeof AddRoute
  '/auth': typeof AuthRoute
  '/profile': typeof ProfileRoute
  '/rediscover': typeof RediscoverRoute
  '/album/$id': typeof AlbumIdRoute
  '/artist/$id': typeof ArtistIdRoute
  '/messages/$handle': typeof MessagesHandleRoute
  '/u/$handle': typeof UHandleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activity'
    | '/add'
    | '/auth'
    | '/profile'
    | '/rediscover'
    | '/album/$id'
    | '/artist/$id'
    | '/messages/$handle'
    | '/u/$handle'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activity'
    | '/add'
    | '/auth'
    | '/profile'
    | '/rediscover'
    | '/album/$id'
    | '/artist/$id'
    | '/messages/$handle'
    | '/u/$handle'
  id:
    | '__root__'
    | '/'
    | '/activity'
    | '/add'
    | '/auth'
    | '/profile'
    | '/rediscover'
    | '/album/$id'
    | '/artist/$id'
    | '/messages/$handle'
    | '/u/$handle'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivityRoute: typeof ActivityRoute
  AddRoute: typeof AddRoute
  AuthRoute: typeof AuthRoute
  ProfileRoute: typeof ProfileRoute
  RediscoverRoute: typeof RediscoverRoute
  AlbumIdRoute: typeof AlbumIdRoute
  ArtistIdRoute: typeof ArtistIdRoute
  MessagesHandleRoute: typeof MessagesHandleRoute
  UHandleRoute: typeof UHandleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/rediscover': {
      id: '/rediscover'
      path: '/rediscover'
      fullPath: '/rediscover'
      preLoaderRoute: typeof RediscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add': {
      id: '/add'
      path: '/add'
      fullPath: '/add'
      preLoaderRoute: typeof AddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$handle': {
      id: '/u/$handle'
      path: '/u/$handle'
      fullPath: '/u/$handle'
      preLoaderRoute: typeof UHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages/$handle': {
      id: '/messages/$handle'
      path: '/messages/$handle'
      fullPath: '/messages/$handle'
      preLoaderRoute: typeof MessagesHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artist/$id': {
      id: '/artist/$id'
      path: '/artist/$id'
      fullPath: '/artist/$id'
      preLoaderRoute: typeof ArtistIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/album/$id': {
      id: '/album/$id'
      path: '/album/$id'
      fullPath: '/album/$id'
      preLoaderRoute: typeof AlbumIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivityRoute: ActivityRoute,
  AddRoute: AddRoute,
  AuthRoute: AuthRoute,
  ProfileRoute: ProfileRoute,
  RediscoverRoute: RediscoverRoute,
  AlbumIdRoute: AlbumIdRoute,
  ArtistIdRoute: ArtistIdRoute,
  MessagesHandleRoute: MessagesHandleRoute,
  UHandleRoute: UHandleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
